---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ntfy-credentials
  namespace: hermes
spec:
  encryptedData:
    token: AgCQhYNJ1o9lcngKtD8rj12V0upv9iDnk22WENtB4EjpsYmpPAaElOq6AVBmrzvYeF3Fniht4i6murZmxnm4HXpd7SX2DsGEGacG2iJ0w0PZIx+GzjTjdCfgit5Zkr6j2tJKHYkfXf+BuaVYpUhzYCZ9zA90XbyLr3jwoCgE6hcnb0+ilqhsLgE4Q/YyOhBDyl6dgZxSN1zhWMBj2xLRGaqNJCtWCdsRz7EeX6n8rOcLl5YIZLjD+/9UfIM+V/NFPBTmcllsI7H0yEJXGNnWufyFz+ABzW6H/gO0ObEcidPnZa8sMqa3SIqeLwGrdVeF6zFB3deJiZzvikRXQtTF5xVJC6xPhQY7GUTyoWYUQmNLJDMPqOPyoxv+nQi7tLUMuzcq2XJqlFz4+hWkoqZjoPCdx7+p+jwqj7QYLlkhnNSC4zbeDfVRKobZd9UM9QEr5xjkKqEgJvoF8fHScyfCM0LzI0ZTx1MyKdEMXCQaanuuhuUopx9x9nDkHU1BuJUl3mw4qtIodQjcjO39/WcXQiVcoYGB9BVXFaribstVKW+H8uvdfZTf46ro4cTOhvdBhR2Gpan+JYyO8bK5mXBzx1nXjRz1lqgVpg13Y8wAYCTdm84RGcSQKnYcKhBemR3yKfvghgwJDjmeCxHaEUMvsw+MeGzZmFGkiUwsarT/ORJJnAPpIpp3RekdmrAQE73R6LDW7A0mB8Zug25Ce7Xl9moJyYr/A0e02VZUDaQMLixzIw==
  template:
    metadata:
      name: ntfy-credentials
      namespace: hermes
