---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gmail-oauth
  namespace: hermes
spec:
  encryptedData:
    client-id: AgBWteUfWgMsPHF6hxO3zyZotCtihqF9AZTmzY+YVM4pgTtnCOkE1M+JdbxyxbdK1Ozfb9hKQM9u1tVopY4UTfohvHOJg2qg2nhQb+3zNGEKzQaqb72Z+lW3s7cjek8ZwypazRMJfhHM7hh7IJZx47jvgM8gej9KDFFKtvd6viARpR+uEPcHHdZs6l0I3i8a39ttGCr5EQvEtjTyV5xvJ1FnWhmjHmnKXUG58eMoO6WA7D+lP2YTc2tMuhgRfyHyR4Fn7DhE4xc4jNwJriU2iZYUCh6wnJoBKDqBxj5ef+khug1HDiN/wfmadZP0RZznwcGmFPLA5D66h6JFPt8Q7iyoNbNK7KrVsg3UvojEgKa7UG8rZklM/wkjyewvZ+QSiJJZILJOZBRWMwAMy6NqCulO9BJc7z7uJCPNvQJseLcswXcvDeTIf/aTwdTg2wqELgWY/rPcoz8vaXRWPKGRbNzZZsBXlcJdxgwXJ35xLf95pv8W4tdE8DIcRYR1Utj2haaDGLoONnyd2yLCafWge2log6VmIBbp1oYcTqnAUz4xr3EpT6cETY+faE6uNXQ0K3kcOkuICte7cb1lcuJUnMyeDnZW+02PnjqY2qFIK7g3sP/pah3dzhcZ64JdrmFOATyAzMUsvVx4EyXwHlsAVNtkHUs57x9ujst9XaPO+o3afJtzy88mq8vq8Lsv9j6YENM=
    client-secret: AgBJZfe1craQo+IY0iR4M/vcj1JWpj7Gwiu5JXC2KuQigbrwAKL0ez5sekQdQ91jDT5440tto+nKl2u3vvSLB1lSAd1vH8iQO/IUQc4G/q+aWCJniq4qd7RuMsV2NctJi+AXgATEjnKiITty5SrXPduC1j6sIGfT5HlfkePvh0+j0E7Od4ix3w/QEOCRDDMWOxa8e57oIJ25zyzM8N1txbZZ6sgPT/ks3pGT6FDSdGbF6TUg7IXX8eif/5pQf1ErsU5UIblRtmSyUyol0YcgTRIw/CBNKDMmNUDhEEAUrcgVsNQwoeynbb2b8t6iaDYRwYv5Yv3LVhXTiclCmJ19vIxvCL1XrkY3ctjzHD5vx/KluWJiIKtEURsUEkXGH05gspg8sshHwd9a4a5g8G97ayG8zA3zWa9w43FbqyL4/ncFyS1s5FLybs4kuGBHYIEI6Nczxs0OEWOhfuyK1+dkD1P9uzpG+EqsSbrLK1+i0oIMWdWRUA/vutZvu2yMUcNknmh2a1fZsv9fMioKHFZnFGZ4wvfPSt4rW1WYQSBta4+Vmo343Kv/64QzcSbEK8Nmpmf7JdaIGPk/RBDpH19jDMn7Tx5m3su9x2w/wX0hs4G5IO3JnCWE2gUcQ97nMeK02NNkqDwI6qCxwuuB5reZPJzKyJd0sJfqr2VZkb3kC3PUcaG7YQtY+D9eZZBF9z7z/+A=
  template:
    metadata:
      name: gmail-oauth
      namespace: hermes
