---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ntfy-credentials
  namespace: hermes
spec:
  encryptedData:
    token: AgDNbW+5Sx8n2HcpWC1OSjx1ZtBT4QE++fItBsIHlL56moGaPs31lNnmjHOVrJQ9t5RgobH9tf70ub2eIFIIq+PKb3ESOo7rNlWStwr5y+MCDipX0rXe4Fd1qrxUnfWJtLo+LdOWqPIV7bpvAg1Uq8qKtIU1kjWXSLYVQ4e0DTaNFOIaZ8tEar8XX124BjnHQVlbv8V3yZSysREgwR2hGQbGywruhIAjcWgD1S0buKbJfX7ylnujn8v8RNyETuRZY1qlPxO8oqPeIO+mqZSRhdSvC1ol3+1Qi7Qwq9R4H2cJ+0b8lNX8Q2Kwlx31zMrtc5yczRJGfwz0t4w49qInjOuBHtYlmt3WT8V2rkqMpXCb4YUwVYZHqAF4Ix9LbPVV2yXnmHXb7HcclX0coNIFmBk4If5kjjt7ct0xWhepAZOpL1Y/Id1IifmGNWLuZSPKmFzu4qIw5TFTw18mcCJ4so24C6zGGYb3ZjjaIbCq0EkLmxwCxj3z/Omj6UkCPzoj2ESUZuqzEA/MrOhx3z+MYb6Bt/+rut73kuTu8U4fzdy0/9IHMxRvWZUh+C3b5Hjfj+hnYe2XIypqzw2WGFcKzFL/rUP1FLLIVL5UzVX6Fnt3ErHaAHCeU2zeQpx82v2ikftMwCv+u/gm2DZ/lJbzJTHvtryEjYq1iGMi/TJ+JUlzia/v72r5PrUGm5EZmBuoUgQ=
  template:
    metadata:
      name: ntfy-credentials
      namespace: hermes
