---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: outlook-oauth
  namespace: hermes
spec:
  encryptedData:
    client-id: AgCskUL0uln9MeuTcio8pKGFvDAsT9rLE5Jtgl/Vsb5FTNW+g1guIKfdnBacEmtfUhIa6lfN/8QI0Uc3s7c2v9VyqTN+I1T0Dxo4zSXbz5UD3Lu+2FSeWbEe6USEqA6NaLIUIWQkqaXqsxnah164QY10ygvdBiutONBdM5U1LCHtFy6RNYgJxyucmKqDY8dspQpvCGedFJ6LZWgEE4G+luZYVVnvW+3nuoaryEwL0sZBzkDt2E/2cdAuaWwuDEW3/JeTGEqD1F5rSu3vs9W83FgDTUMVPAKNtyBZTcRtzcsUiTPUZbXqBGQbCM3ezJGS7oLyMPqfryhK9RQs8i4R75TnbDZ1ubMkUCb83Icas+mXKnzXItbygNxwN6gjcZ7UCTx2GWxAbxdr31jlQRbZaetsPBlrSjWnZLgO2zTz96KsyHGhx7YrdIrdveZxPUlMXXVZEznZ2D13rSGNj9Dm6cij1BaDH4X18toGsCK5+brEfcCBIzkT6yXSCR6DQ4eGC3o3ydI27RhCzao2R2wOWJKR7T39vD689yQWoQypuL3ECKnabqwcYaIknc9QAlGXqiG0EIpO2hJeFyQob540YxZGP+ujPyVDPqDb1Ago4JT9zD3zR4a58DZ55QR2XOPFSzadutm0/iuzjZvYa/fq9g81C1jFT4IBwD5taoLUXbUKs/WA0vJ3YFmXfzh1QJcmhUJjYGUi/jARsURhaDzadD1r079V1lkuzoLmp7Q8/fVre1hedrg=
    client-secret: AgBCcqhvdRmUNlA/6xFoexsauBlgGRqMJjHq7Omn1D4/4fPLFDp8ebm//s2tVBdit5qT05c1TUKwgO5bSBNPltooQBac3UqPkBFW+kfql87jOVw2Yf3U2r7zZFjaSXbFNQCQkIk2UY75ExbSsSdikQq6gdHXiiyvj8J1g6XmHQHTPgePT8QDnm3D5whKalXHjNgrI6KvoYHBmUZGqvEbObcBRtqLu0tz269jcPre3arHQtD+cjOsvtKmYg1yTHyOo5WM++WazwE6kTbbc+GDv3TQb9Uo0QRBuGzYg9m/yPTTF7ZC62X7zl+dBHnl7ykpM875BvjlbpVafLYYvwZBtf638RpzcbKmtFM3ccPTo3f60GQIcKKygT2gXTVV07ESAqdKOtWcQwq84OKYyFfeECacTz1cAEleosp8ngU0mggfOMJgeV5g6eix17ic9fzS8t7H1ZbVSqZDjoanCPgA29wWo5P3xQrKwiWvG3dFXogMqTqJ6oGX7dW5zIRmApx4+hKIzXJYO/QLIf4vAj/3BjQVGX/gsycQo4iYYz+9ynh6OQblyCTpAo9DS5B9RJeyGArZj6vwVDQQ51LJtIi5epBCrXYRhN1TBgWvNwILh1eDndkQuZEcZ+W7JoAAljmnDc7Q8g1loJHcEDe7DcMrSK2ctQOWMgFIpA21gc165syOTlgxRwRq7Ni4eSeRHb2gVdlcwlxMnAJQmyujdu7JPgBTwONqiWQfmxwx9mZnoGzggPDtvENqiLXI
  template:
    metadata:
      name: outlook-oauth
      namespace: hermes
