---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-db
  namespace: hermes
spec:
  encryptedData:
    password: AgBe63GZS8bg+p8MDllCOZBhajtfrmtC7wZKh7SsSh6in7BZ+lvhxHvzJ66bf1ROtKGXV3J/CiRYZ+eyOig66xMjkcsuQy81WbTdjhuhA3biZLBFRE9dk8itzivMJik5AkAxUJszKdrjXTvJXgnlA2VnXeoXO0/t0eDdkyVJr7D1W+w1nIJulZY+EJ24uV0lShDq7xPmIjAD4mDl2FoagjtQTdNajKVN/UsiwuOA1iM9P+P3GtBNOp/voJhgmuKSDP1rerg0FazAYLsFXGO5c5hvQH0+5FiFhA+rJ/zXv+e+zDNX3alhH7okOggHW+6W0siJgaslYh7ShE5/w1Gbk0mB+5hRRtOqKnPlgWN+j89tISIDN+xtBWsdn1s9Nf2kztn56vGc/Qb4+t1rmJCIXj+WnH2mNtyuKLJtWDNZ4J63PwCuInacqT9Hzdb4l6hSJAWZeLFOGZxeUJohOAiniwmqyRPSpAdjXJeUpLq0ZtTx7dQbgbG2XXm9RS97TlalzsacQyJh/3mXWW5hkUyxkex+2qVLi6ADudxvGBLiF8mnMmsxZmup7F8qVbI70c+E0otrnf6MId9Zr37duK/q8KqEpVK5Vz2kh5tGS1GBf8Eghm6zaFhg/H2P5ADpakEVbtm4sl8wuPeghYDhM9R2pjL+mLoG+avh0qQyjTE8xnroJZ1+rM5vgF32+CrKYSyfNXUXXZk0NrNn4oY/u/ePuTq+5D/YGqxyQYJrn7V1+2ip7Q==
    username: AgBC+qBaYmkKF8FadQ4x1lA9rjkRI8OE50S1cPg1RBlIbQOlcOccL1Ij7ZVh8rD5ZzrMRm1wMo9l46cUM8ADTVf+ftbeDDJLOENTLKbBIoxIsX3iin8n4Al2qthpBmTNy0tvyn4/Svc67KO0AUjzHxZgCys9FmGHucYb4yt6jopZFw+VcFvAYiuryZ60IOe4inSVxDB0rio9kqSi5v3ou3M8y8EqSk5BDRW20UOvpolqspfJfctYMhBjA4C10VGTMAs/5Tg3QRAH+C8CYZbpn0dnTmDullf/ZBtNTMGJ+UH22PE5DOmS8h3fTF+C7/6cvwdhP99XpaIixy4+UmO1vGDqnYTfT0yO868zlD0c+rrH94URGtSY++L8B3gsEIh9pi29OIXYw1bNYGs9vj5ybl2Wz5O14xkc9Ype6eVm3z7QH08GaTtsxwkIs7mlj6j1eRdGGgUDlBJfi9H1xTiVX6pQnbUPOQOv8bkwEtkBpkdj4c8bQVUQt8hkwFqAD91L45ABsNxXf1fszH5s0WIycvSJc6TkrB+hqF72vBE4OUz1Ojkif+PHtj6NdL9/HtN7XGySajHBTX97RpL6psoNsj7eRKKwGru3+R/J7RL4sabASKX3a/l5xZPGpEuDWo9TDDWlA5+niQfTMjK3ExYB3HrLUJ3RFCJ3oigqdLDwrziMr8PlNj140UROyEvIbPwn/O8Rpu2koUw=
  template:
    metadata:
      name: hermes-db
      namespace: hermes
