---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: claude-oauth-token
  namespace: hermes
spec:
  encryptedData:
    token: AgCG0KXBE0BSlHzSYewqFjimgAx1bzPkc/kAl1KBLMe/L2GrEerrXKJVA5JCNJlV81uHHuMH5kofetZBIAZpXi16RJz0dAiFeKzfR7JWyYspFrl3GYjIng0Ahft834t9TTdqlKCR79xBoybAKQqL63A1BukkXMejpj8YZnq7aVOJmhmetac4U0YvurVTidLHiz0lUSUvYP/D+Mdup8gSaMd5iUd45zbpK2gGgxB24nuFHBe2HSUPcuF4JVunGBsXsatRbRE4czZErUbGB4zDP8okmxASF0iI4WCyhVLITYSWEb+bW3bgi57UDssEVsqhFCrlBfuwkXisZmDa57akU43sBmV0TVlo0BexodWDA+rrmtMxzl2PXu04KkfELCrULr8gHyOn0IvQbUKgYlaO1ka31L5wX+VJns3O3Ml6/BvDz8SXzBbkSVnF0VwK5MBmv+jQPuBZUA0qZbVkFl23/L/0c4h5iS2MJ/7/eRkRw1ts8SmAq98M1icu2uQdCEq3rTaRhV176dJ5GtIvDTCLcRU/6h/VFugtQ3pUCdPzHnHELJ9ovGi72xzSL+N0OVTX2iWyaxDEkoGUSQu9yAKBEyQHnKG7k2lvlp0RDuXb2Xx1Twe9fBuOMcsDvUYgitulYGOD/q1pxQFldRu0ikWnt20S5QSIaHw60c//Nd8EKP5UAqdZYxqPxKAb6x5jrwSoMYwms5bTaZHucDzblbjS4Z2TfmwmoNiUFeq0EXJo8lVuGBXkvL4WM2Tj6Qc8V5sW1fFhz+hLOJyaQ/b2sWSjY6n41g37O8KMZIfs1VPsFMB2F8yiQvErsB/w7I8jPZa2Eh96u00j8gFpTQf9h3M=
  template:
    metadata:
      name: claude-oauth-token
      namespace: hermes
