---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gmail-oauth
  namespace: hermes
spec:
  encryptedData:
    client-id: AgBysfHItgJNNyccL9ylONGCH4WWLGl7l9wFwTyoaLzpgIL/2RN/T2QZskleQBrRN1hj6QfqApdGp4St+Tu7cxjat7zWgO/YTYip0y3HpVOG90ehzbRB0PfcDKGuIiFBy3omo/uJ7tf8Pw7yFxr9HHeXnuux84+asssE+VvX62jBrRj0rIRsd38CRMPnvwQLMWZ4MTNv6cUOwhHoGY2C3J9Vw5XiDzs7vbO3Nt5qf0SUV5q65+VLN2jz0vj6DCbqOW2o1mirJpws2M5bWxE+lsZmCCeE5IGJE1YiRL1MlwStVFbLf6elDZOiK2Z+HC2dF4VyxjsKveIYe+axP7qFWNjAkb8jFufJbMITZZUoG7KISvxsGv1/MAuSN+EKyi41XZAn42KMiL9PfERdzp+p3ClBoz52+ZP9b4tSeI2BCDgNZs3QtyS4Um/E3f1uIdtL+7/6khX36ry9QwhvTOszZQJbSaGfKlXmLEM5gZnww6aKe9dv1owGLxnJmPzfs2c/11npnjlpeRjTffimHrUwpbgJmSd61XiL6zdVRS1ZaBvSJbgpcwXr5rhEFUtjIUmC15Fr2xYfPU0Nw1FeansxuqCnx8ft2lj0xTO2rViWJSWEQeM4tuhotsWU0JmvmJgleN/EyjxsjLGlXw6PSRDrlLf2GdMCl/N8oMxF+WevFOdwLLcPvlnQFGKxC7JuMdI+7Vat7Dnfb1HHsJr1CGt5Nbom43WdPqa537WlGqj4XU60WTijMCZgVmwQu8JOZt/6iNCfyYg2xL9bYm0Cx/fCRv9Ex0J4B7W5JPQ=
    client-secret: AgCBR/7Fyz6EvMbGE3ufxD7dY2wr7ZWdzNM6zsdHmtMl/+ugXnJVYIbYbYqmjv+n/4dRRKxgdG1/BDRXWel9RKBwlP5yBLTqMGUSVHsv8yvmt7VQnRyMDWNgl2hwD3Ji2QHiQzOCfLOzWvngyW7lBnZtTMfuySNUm6VXO6+k0eDkPvEKd4Q3swH84UcYVvqwWkd/O6ZuEod8FI9tosil1yxoPEV9D2iFuWdQOVrKQI4ExdUKWRI6RxIThZo/sxlyT1mc0oi1m5igBFYyhJwYBknRTw+P2GcRVhD94tjiW1/l/63P+SEd5QrbGzqLg0Oz66ztK0SPJsCONzjRpljohLnCML8AW5YXhUSg6QgTnHUjFK89bqVeGjF7/LSP6L+PLI5YeS2YuXBDcSnn1uzgjbXXeABkTzuq+yyVnNDdCenNgpefBJ+yDNAH/vgItBoj77L5ujNvx+mJNOuXpznp5RSOZc2+ILkkl2QXD+R854NSGt216oS0Fxnj5DgMV9Yx0UpxsZV3PHsEAtfrsKJYYu6w1s8/hRRlqk3C+KVMX3nKVsXnYCF/o24up51ETA7/4nMwIo9bV9a6PTAvwwBhwtuvaUaNDn/GQJiBNpR7Fzore7ZtgvwMoCD9EreJJgIB03MEyxeAmzZmXaSgeM/e8gHJ4wEo9OjvHceR2NSahCf2xFW3rZjbOXLT2vdXdM2PPxfwQ5jNcHQsMxWBLm1+H8Cpgohcl0T8dyIBCD6W1keOg0AjTg==
  template:
    metadata:
      name: gmail-oauth
      namespace: hermes
