---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alert-webhook-secret
  namespace: hermes
spec:
  encryptedData:
    token: AgCRGKQ7iJoME6Nz01QVLuK4zBhX+AE7NA4Etkhvrx6hnrhdy8BmiZaySZ4mWmpNgIJSfLQI50KcrLn8PS27pzkprP/hgkHiKaBBJZlYZLRz1OT3U4qYH+tcM/k6XCpGLrinkC65UN6wkKWyL9bsrLzb63B8v5nalKkq3+BFhmaJFA3Jd/LiBrPaGgT9wJWFixrugSGGYNWfqRH1YqWX1HAkUKWtukyAZEVX6d3xnW9Idz5J6m9OSHcQq1M2cCY1ZkL+z4jSZPYH78oOkExELPt40vwjyk/R2k+bDlrpNVTVcSxmgUG9pqgg1lgSyZEATh4Oau4ur9ixh/MtkCL+LU8P2JIwlQnF0isIwiheQaE2r6NMGDxg9ZAwLVaJ7dbwxJDQOX1tPLdZ91h2JfICXAoDwVhlrqh3uY2uxp/2OLyUc75WZv6Xu1/pmNOTtQ81UfSHtR2txCq9hc4aLsY7+FBY/aXsFhz5Z0Qd8GyhhYPdCNiS5eyxggip1HWoSgKci0Azf65uukMiBk6B29vPwXr51nccieS9DOo6I1sG0e6ikfbpMlJDss5jAwMGmcpNIizQETGIocvuRiTLFxGRZxEv4w7ckIcbQBr/GdJ2lRWzK/UwBtzPv3jIOmOsKGnjC1c9VkXvrvi+IdTDivtvXSu+GSdwPmtGFg7EijwgEICxoAJqmsRXCFV4tohk3jzPT8SR8n1AeO/ZL7QkZhk6kvUq0CcejygBZwVpN6bOwsivIhJxHdRz2amCnmq3+eKKrAeYDqqMXTJ0BLFYpIDIf5ve
  template:
    metadata:
      name: alert-webhook-secret
      namespace: hermes
